/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FINALfahrrad.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/FINALfahrrad-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.414, -2.927, 4.911]} rotation={[Math.PI, -0.005, Math.PI]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials.street} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['roow.001']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['ручка.001']} />
      </group>
      <mesh geometry={nodes.Tree003.geometry} material={materials['Material.122']} position={[-8.374, -2.921, 14.085]} scale={0.278} />
      <group position={[4.893, -2.921, 15.256]} scale={0.278}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.064']} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Material.063']} />
      </group>
      <mesh geometry={nodes.Grass005.geometry} material={materials.Bush} position={[3.506, -2.88, 16.241]} rotation={[Math.PI, -1.548, Math.PI]} scale={0.389} />
      <mesh geometry={nodes.Grass001.geometry} material={materials['Material.015']} position={[4.828, -2.88, 15.516]} rotation={[2.945, -1.137, 2.819]} scale={0.389} />
      <mesh geometry={nodes.house124.geometry} material={materials.wood} position={[-4.191, 2.698, 16.772]} rotation={[1.592, 0, 0]} scale={[3.67, 1.626, 2.516]} />
      <mesh geometry={nodes.house105.geometry} material={materials.wood2} position={[-6.987, 1.985, 15.322]} rotation={[1.572, 0, 0]} scale={[5.697, 2.524, 3.906]} />
      <mesh geometry={nodes.house.geometry} material={materials.dark} position={[-1.634, -5.399, 8.745]} scale={[4.852, 2.149, 3.327]} />
      <mesh geometry={nodes.Door.geometry} material={materials['Door.001']} position={[-0.385, -1.028, 12.055]} scale={1.613} />
      <group position={[-7.689, -2.875, 13.615]} scale={0.219}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.118']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.119']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.120']} />
      </group>
      <group position={[-8.096, -1.611, 13.108]} rotation={[0, 0.922, 0]} scale={0.219}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['Material.123']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.124']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.125']} />
      </group>
      <group position={[4.634, -1.838, 11.089]}>
        <mesh geometry={nodes.Cube146.geometry} material={materials['Handlebar.002']} />
        <mesh geometry={nodes.Cube146_1.geometry} material={materials['Wheel.001']} />
        <mesh geometry={nodes.Cube146_2.geometry} material={materials['Pedals_Seat.001']} />
        <mesh geometry={nodes.Cube146_3.geometry} material={materials['Frame.002']} />
        <mesh geometry={nodes.Cube146_4.geometry} material={materials['Chain.002']} />
      </group>
      <mesh geometry={nodes.Cube125.geometry} material={materials.wood} />
      <mesh geometry={nodes.Cube244.geometry} material={materials.wood2} />
      <mesh geometry={nodes.Cube137.geometry} material={materials['Material.136']} />
    </group>
  )
}

useGLTF.preload('/FINALfahrrad-transformed.glb')
