/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 campusModel.glb --transform
*/

import React, { useEffect } from "react";
import { useFBX, useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { useControls } from "leva";

export function CampusModel(props) {
  const { nodes, materials } = useGLTF("/Models/campusModel-transformed.glb");
  // const { scene } = useGLTF("/Models/Landscape.glb");
  const model = useFBX("/Landscape.fbx");
  const { camera } = useThree();
  const { position, rotation } = useControls({
    position: {
      value: [268, 37.2, -136] ,
      step: 2,
    },
    rotation: { value: [0.2, 2.4, -0.2], step: 0.2 },
    fov: { value: 45, step: 5 },
  });

  useEffect(() => {
    camera.position.set(...position);
    camera.rotation.set(...rotation);
  }, [position, rotation]);
  console.log(model);
  return (
    <group name='campus' {...props} dispose={null}>
      <group position={[16.083, -23.741, 31.44]} scale={11.23}>
        <mesh
          name='campus'
          geometry={nodes.Cube002.geometry}
          material={materials.Box}
        />
        <mesh
          name='campus'
          geometry={nodes.Cube002_1.geometry}
          material={materials.Ground}
        />
      </group>
      <mesh
        name='campus'
        geometry={nodes.Cloud_1001.geometry}
        material={nodes.Cloud_1001.material}
        position={[-14.503, 36.564, 112.497]}
        rotation={[0, -0.289, 0]}
        scale={7.169}
      />
      <mesh
        name='campus'
        geometry={nodes.Plane.geometry}
        material={materials["Material.007"]}
        position={[-119.314, -0.415, 75.481]}
        rotation={[-1.564, 0, 0]}
        scale={-382.573}
      />
      <group
        position={[104.596, -13.259, -117.006]}
        rotation={[-Math.PI, 1.569, -Math.PI]}
        scale={[7.705, 7.705, 15.591]}
      >
        <mesh
          name='campus'
          geometry={nodes.Plane003.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          name='campus'
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          name='campus'
          geometry={nodes.Plane003_2.geometry}
          material={materials["Cobblestone sidewalk"]}
        />
        <mesh
          name='campus'
          geometry={nodes.Plane003_3.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <mesh
        name='campus'
        geometry={nodes.Plane023.geometry}
        material={materials.Ground}
      />
      <mesh
        name='campus'
        geometry={nodes.Plane019.geometry}
        material={materials.Ground}
      />
      <mesh
        name='campus'
        geometry={nodes.Cylinder003.geometry}
        material={materials.Ground}
      />
      <mesh
        name='campus'
        geometry={nodes.Cylinder003_1.geometry}
        material={materials.Ground}
      />
    </group>
  );
}

useGLTF.preload("/campusModel-transformed.glb");
