/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FINALgeb1.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, PresentationControls } from "@react-three/drei";
import { useControls } from "leva";

export function FINALgeb1(props) {
  const { nodes, materials } = useGLTF("/Models/FINALgeb1-transformed.glb");

  const { pos, rot } = useControls("geb1", {
    pos: {
      //{"pos":[90,8,-152]}
      value: [56, 6, -130],
      step: 2,
    },
    rot: { value: [0, -1.6, 0], step: 0.2 },
  });

  return (
    <PresentationControls enabled={true} azimuth={[-0.2, 0.2]} polar={[0, 0]}>
      <group
        name='building1'
        {...props}
        dispose={null}
        position={pos}
        rotation={rot}
        scale={2}
        onClick={() => props.setActiveState(1)}
      >
        <group
          position={[12.741, -2.853, 2.876]}
          rotation={[-Math.PI, 1.566, -Math.PI]}
        >
          <mesh
            geometry={nodes.Plane002.geometry}
            material={materials.street}
          />
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials["roow.001"]}
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials["ручка.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane009.geometry}
          material={materials["glass.002"]}
          position={[8.376, 1.019, 10.446]}
          rotation={[0.001, 0, -3.141]}
        />
        <mesh
          geometry={nodes.Cube185.geometry}
          material={materials["Material.150"]}
          position={[0.961, 5.042, -2.031]}
        />
        <mesh
          geometry={nodes.Cube122.geometry}
          material={materials["Material.188"]}
          position={[6.941, -1.897, -1.525]}
        />
        <mesh
          geometry={nodes.Cube094.geometry}
          material={materials["Material.032"]}
          position={[5.76, 4.78, 2.328]}
          scale={1.459}
        />
        <mesh
          geometry={nodes.Cube092.geometry}
          material={materials["Material.034"]}
          position={[-5.217, 4.504, 7.711]}
        />
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.Geb2}
          position={[5.923, 0.711, 3.765]}
          rotation={[Math.PI, -1.567, Math.PI]}
          scale={3.508}
        />
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials.Black}
          position={[9.735, -2.32, -7.134]}
          rotation={[0, 0.117, 0]}
          scale={0.167}
        />
        <mesh
          geometry={nodes.Circle032.geometry}
          material={materials.Metallic}
          position={[9.735, -2.298, -7.134]}
          rotation={[0, 0.117, 0]}
          scale={0.167}
        />
        <group position={[-19.052, -2.81, -4.504]} scale={0.301}>
          <mesh
            geometry={nodes.Cylinder011.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            geometry={nodes.Cylinder011_1.geometry}
            material={materials["Material.008"]}
          />
        </group>
        <group position={[-17.695, -2.806, -3.659]} scale={0.282}>
          <mesh
            geometry={nodes.Cylinder010.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Cylinder010_1.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group position={[-9.132, -2.748, 12.584]} scale={0.275}>
          <mesh
            geometry={nodes.Cube049.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Cube049_1.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Cube049_2.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <mesh
          geometry={nodes.Grass001.geometry}
          material={materials["Material.004"]}
          position={[-9.185, -2.781, 12.714]}
          rotation={[Math.PI, -0.426, Math.PI]}
          scale={0.38}
        />
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Material.010"]}
          position={[9.832, -2.694, -1.995]}
          rotation={[-1.57, 0, -1.573]}
        />
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials["Material.012"]}
          position={[9.832, -2.694, 9.7]}
          rotation={[-1.57, 0, -1.573]}
        />
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["Material.163"]}
          position={[10.129, -1.897, -1.525]}
        />
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["Material.189"]}
          position={[9.498, 5.094, 2.189]}
        />
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials["Material.009"]}
          position={[10.167, 2.41, 4.076]}
          rotation={[0, 0, -1.57]}
        />
        <mesh
          geometry={nodes.Plane047.geometry}
          material={materials["glass.018"]}
          position={[10.384, -3.327, 7.937]}
          rotation={[-1.57, 0, -1.573]}
        />
        <mesh
          geometry={nodes.Plane049.geometry}
          material={materials["Material.173"]}
          position={[10.167, -0.127, 4.076]}
          rotation={[0, 0, -1.57]}
        />
        <mesh
          geometry={nodes.Plane050.geometry}
          material={materials["Material.175"]}
          position={[10.314, -0.127, 3.999]}
          rotation={[0, 0, -1.57]}
        />
        <mesh
          geometry={nodes.Plane051.geometry}
          material={materials["Material.176"]}
          position={[10.314, -0.127, 3.952]}
          rotation={[0, 0, -1.57]}
        />
        <mesh
          geometry={nodes.Text.geometry}
          material={materials["Material.179"]}
          position={[10.379, -0.035, 4.601]}
          rotation={[-2.76, 0.003, -1.567]}
          scale={1.075}
        />
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials.Material}
          position={[6.941, 5.167, -1.525]}
        />
        <mesh geometry={nodes.Plane058.geometry} material={materials.Black} />
        <mesh
          geometry={nodes._Light_Area_Of_Street_lamp_B.geometry}
          material={materials["Emission_ Color_Palette"]}
          position={[8.924, -2.832, 0]}
          scale={0.549}
        />
        <mesh
          geometry={nodes.Base_Of_Street_Lamp_B.geometry}
          material={materials.Metal_Color_Palette}
          position={[8.924, -2.832, 0]}
          scale={0.549}
        />
      </group>
    </PresentationControls>
  );
}

useGLTF.preload("/FINALgeb1-transformed.glb");
