/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FinalGeb6.glb --transform
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export function FinalGeb6(props) {
  const { nodes, materials } = useGLTF("/Models/FinalGeb6-transformed.glb");
  const { position, rotation } = useControls("GEB1", {
    position: {
      value: [69, 2, 72],
      step: 2,
    },
    rotation: { value: [-0.1, 1.2, 0], step: 0.2 },
  });
  return (
    <group
      onClick={() => props.setActiveState(6)}
      name='building2'
      {...props}
      dispose={null}
      position={position}
      rotation={rotation}
      scale={1.7}
    >
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.Geb2}
        position={[0.009, 0.715, 1.898]}
        rotation={[Math.PI, -1.567, Math.PI]}
        scale={3.508}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.glass}
        position={[4.483, -1.787, 0]}
        rotation={[0, 0, -1.57]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.011"]}
        position={[4.51, -0.336, 0]}
        rotation={[0, 0, -1.573]}
      />
      <group
        position={[4.582, -2.07, -2.693]}
        rotation={[0, -0.629, 0]}
        scale={0.019}
      >
        <mesh
          geometry={nodes.Mesh.geometry}
          material={materials.dbl_Layer0_001}
        />
        <mesh
          geometry={nodes.Mesh_1.geometry}
          material={materials.dbl_Layer0_002}
        />
        <mesh
          geometry={nodes.Mesh_2.geometry}
          material={materials.dbl_Layer0_003}
        />
        <mesh
          geometry={nodes.Mesh_3.geometry}
          material={materials.dbl_Layer0_005}
        />
        <mesh
          geometry={nodes.Mesh_4.geometry}
          material={materials.dbl_Layer0_008}
        />
      </group>
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Material.016"]}
        position={[4.515, -2.627, -4.013]}
        rotation={[1.634, -0.005, -1.564]}
        scale={1.656}
      />
      <mesh
        geometry={nodes.Text003.geometry}
        material={materials["Material.062"]}
        position={[4.305, -2.595, -4.989]}
        rotation={[1.583, -0.006, -3.135]}
        scale={1.597}
      />
      <mesh
        geometry={nodes.Cube089.geometry}
        material={materials["Material.001"]}
        position={[0.185, -5.357, -2.472]}
        rotation={[Math.PI, -1.566, Math.PI]}
        scale={0.098}
      />
      <mesh
        geometry={nodes.Cube092.geometry}
        material={materials["Material.034"]}
        position={[2.544, 4.254, 3.647]}
      />
      <mesh
        geometry={nodes.Cube093.geometry}
        material={materials["Material.033"]}
        position={[-0.079, 4.784, 3.647]}
      />
      <mesh
        geometry={nodes.Cube094.geometry}
        material={materials["Material.032"]}
        position={[-0.104, 4.784, 0.47]}
        scale={1.459}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={materials["Material.036"]}
        position={[13.836, -1.856, -5.797]}
      />
      <mesh
        geometry={nodes.Cube104.geometry}
        material={materials["Material.035"]}
        position={[7.206, -0.904, 7.515]}
        scale={0.098}
      />
      <mesh
        geometry={nodes.Cube122.geometry}
        material={materials.Material}
        position={[3.032, -1.893, 6.433]}
      />
      <mesh
        geometry={nodes.Cube057.geometry}
        material={materials["Material.073"]}
        position={[0.193, 3.925, 21.099]}
        scale={2.503}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Material.091"]}
        position={[2.741, -1.613, 21.919]}
      />
      <group position={[4.882, -1.785, 8.309]}>
        <mesh
          geometry={nodes.Cube131.geometry}
          material={materials["Handlebar.001"]}
        />
        <mesh geometry={nodes.Cube131_1.geometry} material={materials.Wheel} />
        <mesh
          geometry={nodes.Cube131_2.geometry}
          material={materials.Pedals_Seat}
        />
        <mesh geometry={nodes.Cube131_3.geometry} material={materials.Frame} />
        <mesh
          geometry={nodes.Cube131_4.geometry}
          material={materials["Chain.001"]}
        />
      </group>
      <group
        position={[-1.427, -2.853, -7.443]}
        rotation={[Math.PI, -0.005, Math.PI]}
      >
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials.street}
        />
        <mesh
          geometry={nodes.Plane002_2.geometry}
          material={materials["roow.001"]}
        />
        <mesh
          geometry={nodes.Plane002_3.geometry}
          material={materials["ручка.001"]}
        />
      </group>
      <mesh
        geometry={nodes.Circle018.geometry}
        material={materials.Blue}
        position={[5.758, -2.257, 0.862]}
        scale={0.213}
      />
      <mesh
        geometry={nodes.Circle017.geometry}
        material={materials.Metallic}
        position={[5.722, -2.37, 0.862]}
        scale={0.213}
      />
      <group position={[7.416, -2.806, 9.03]} scale={0.115}>
        <mesh
          geometry={nodes.Circle.geometry}
          material={materials.Metal_Color_Palette}
        />
        <mesh
          geometry={nodes.Circle_1.geometry}
          material={materials["Emission_ Color_Palette"]}
        />
      </group>
      {/* <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cube003_1.geometry}
        material={materials["Material.001"]}
      /> */}
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials["Material.011"]}
      />
      {/* <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials["Material.035"]}
      />
      <mesh
        geometry={nodes.Cube052.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cube059.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cube060.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Cube132.geometry}
        material={materials["Material.011"]}
      />
      <mesh
        geometry={nodes.Cube089_1.geometry}
        material={materials["Material.035"]}
      />
      <mesh
        geometry={nodes.Cube089_2.geometry}
        material={materials["Material.035"]}
      />
      <mesh
        geometry={nodes.Cube089_3.geometry}
        material={materials["Material.035"]}
      /> */}
    </group>
  );
}

useGLTF.preload("/FinalGeb6-transformed.glb");
