/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FINALgeb4.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, PresentationControls } from "@react-three/drei";
import { useControls } from "leva";
export function FINALgeb4(props) {
  const { nodes, materials } = useGLTF("/Models/FINALgeb4-transformed.glb");
  const group = useRef();
  const { pos, rot } = useControls("geb4", {
    pos: {
      //{"pos":[50,-5,82]}
      value: [50, -5, 82],
      step: 2,
    },
    rot: { value: [0, -1.45, 0], step: 0.2 },
  });
  return (
    <PresentationControls enabled={true} azimuth={[-0.2, 0.2]} polar={[0, 0]}>
      <group
        onClick={() => props.setActiveState(4)}
        name='building4'
        ref={group}
        {...props}
        dispose={null}
        position={pos}
        rotation={rot}
        scale={2.2}
      >
        <mesh
          geometry={nodes.Street_FLF072.geometry}
          material={materials["Bush.003"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF078.geometry}
          material={materials["Material.082"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <group
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane100.geometry}
            material={materials["Material.080"]}
          />
          <mesh
            geometry={nodes.Plane100_1.geometry}
            material={materials["Material.081"]}
          />
        </group>
        <group
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane107.geometry}
            material={materials["Material.078"]}
          />
          <mesh
            geometry={nodes.Plane107_1.geometry}
            material={materials["Material.079"]}
          />
        </group>
        <group
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane114.geometry}
            material={materials["Material.066"]}
          />
          <mesh
            geometry={nodes.Plane114_1.geometry}
            material={materials["Material.065"]}
          />
        </group>
        <mesh
          geometry={nodes.Street_FLF274.geometry}
          material={materials["Material.083"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Text004.geometry}
          material={materials["Material.074"]}
          position={[2.912, -2.472, 10.155]}
          rotation={[1.575, 0.01, -1.94]}
          scale={0.154}
        />
        <group
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane002.geometry}
            material={materials.street}
          />
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials["roow.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Text.geometry}
          material={materials["Material.016"]}
          position={[0.323, -2.756, 5.594]}
          rotation={[-3.121, -0.005, -1.564]}
          scale={0.736}
        />
        <mesh
          geometry={nodes.Street_FLF002.geometry}
          material={materials["ручка.001"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF128.geometry}
          material={materials["Material.072"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF129.geometry}
          material={materials["Material.071"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF138.geometry}
          material={materials["Material.073"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF149.geometry}
          material={materials["Material.001"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF152.geometry}
          material={materials.Geb2}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF166.geometry}
          material={materials["Material.002"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF167.geometry}
          material={materials["Material.003"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF168.geometry}
          material={materials["Material.004"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF171.geometry}
          material={materials["Material.007"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF172.geometry}
          material={materials["Material.008"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF241.geometry}
          material={materials["Material.034"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF242.geometry}
          material={materials["Material.033"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF243.geometry}
          material={materials["Material.032"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF244.geometry}
          material={materials["Material.035"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF270.geometry}
          material={materials["Geb2.001"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF298.geometry}
          material={materials["dbl_Layer0_001.006"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF299.geometry}
          material={materials["dbl_Layer0_002.006"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF307.geometry}
          material={materials["dbl_Layer0_003.006"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF311.geometry}
          material={materials["dbl_Layer0_004.006"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF315.geometry}
          material={materials["dbl_Layer0_005.006"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF317.geometry}
          material={materials["dbl_Layer0_006.006"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF319.geometry}
          material={materials["dbl_Layer0_007.006"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF320.geometry}
          material={materials["dbl_Layer0_008.006"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF367.geometry}
          material={materials.glass}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF368.geometry}
          material={materials["Material.010"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF372.geometry}
          material={materials["glass.001"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF381.geometry}
          material={materials["Material.036"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF069.geometry}
          material={materials["Material.067"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <group
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane092.geometry}
            material={materials["Material.075"]}
          />
          <mesh
            geometry={nodes.Plane092_1.geometry}
            material={materials["Material.076"]}
          />
          <mesh
            geometry={nodes.Plane092_2.geometry}
            material={materials["Material.077"]}
          />
        </group>
      </group>
    </PresentationControls>
  );
}

useGLTF.preload("/FINALgeb4-transformed.glb");
