/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FINALgeb7.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, PresentationControls } from "@react-three/drei";
import { useControls } from "leva";

export function FINALgeb7(props) {
  const { nodes, materials } = useGLTF("/Models/FINALgeb7-transformed.glb");
  const group = useRef();
  const { pos, rot } = useControls("geb7", {
    pos: {
      //{"pos":[-160,7,-32]}
      value: [-160, 7, -32],
      step: 2,
    },
    rot: { value: [0, 1.7, 0], step: 0.2 },
  });
  return (
    <PresentationControls enabled={true} azimuth={[-0.05, 0.05]} polar={[0, 0]}>
      <group
        onClick={() => props.setActiveState(7)}
        ref={group}
        {...props}
        dispose={null}
        position={pos}
        rotation={rot}
        scale={3}
      >
        <group
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane002.geometry}
            material={materials.street}
          />
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials["roow.001"]}
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials["ручка.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Text003.geometry}
          material={materials["Material.062"]}
          position={[-6.665, -1.063, 10.481]}
          rotation={[1.559, 0.006, 0.023]}
          scale={0.725}
        />
        <mesh
          geometry={nodes.Plane009.geometry}
          material={materials["glass.002"]}
          position={[-9.19, -1.843, 10.379]}
          rotation={[0, 1.556, -1.57]}
        />
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials.glass}
          position={[-14.01, -1.843, 5.363]}
          rotation={[-Math.PI, 0.017, 1.572]}
        />
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["Material.080"]}
          position={[-2.379, -0.01, 10.614]}
          rotation={[0, -1.523, 0]}
          scale={2.827}
        />
        <mesh
          geometry={nodes.Text001.geometry}
          material={materials["Material.077"]}
          position={[-13.132, -2.756, 10.481]}
          rotation={[1.559, 0.006, 0.023]}
          scale={3.986}
        />
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials["Material.079"]}
          position={[-4.12, -1.962, 11.572]}
          rotation={[0, -0.299, 0]}
          scale={1.303}
        />
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["Material.081"]}
          position={[-1.027, -2.024, 12.624]}
          rotation={[0, -0.299, 0]}
          scale={1.303}
        />
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["Material.082"]}
          position={[2.676, -2.024, 13.509]}
          rotation={[0, -0.299, 0]}
          scale={1.303}
        />
        <group
          position={[-18.701, -2.927, 3.182]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane123.geometry}
            material={materials["Material.096"]}
          />
          <mesh
            geometry={nodes.Plane123_1.geometry}
            material={materials["Material.097"]}
          />
          <mesh
            geometry={nodes.Plane123_2.geometry}
            material={materials["Material.098"]}
          />
        </group>
        <group
          position={[-18.701, -2.927, 3.182]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane121.geometry}
            material={materials["Material.094"]}
          />
          <mesh
            geometry={nodes.Plane121_1.geometry}
            material={materials["Material.095"]}
          />
        </group>
        <mesh
          geometry={nodes.Street_FLF082.geometry}
          material={materials["Material.015"]}
          position={[-18.701, -2.927, 3.182]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        {/* <mesh geometry={nodes.Torus.geometry} material={materials['Material.075']} /> */}
        <mesh
          geometry={nodes._Light_Area_Of_Street_lamp_B.geometry}
          material={materials["Emission_ Color_Palette"]}
          position={[-6.307, -2.917, 15.215]}
          scale={0.648}
        />
        <mesh
          geometry={nodes.Base_Of_Street_Lamp_B.geometry}
          material={materials.Metal_Color_Palette}
          position={[-6.307, -2.917, 15.215]}
          scale={0.648}
        />
      </group>
    </PresentationControls>
  );
}

useGLTF.preload("/FINALgeb7-transformed.glb");
