/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FinalGeb2.glb --transform
*/

import React from "react";
import { useGLTF, PresentationControls } from "@react-three/drei";
import { useControls } from "leva";
export function FinalGeb2(props) {
  const { nodes, materials } = useGLTF("/Models/FinalGeb2-transformed.glb");

  return (
    <PresentationControls
      enabled={true}
      azimuth={[-0.2, 0.2]}
      polar={[0, 0]}
    >
      <group
        name='building6'
        {...props}
        dispose={null}
        position={[-12, -1, -12]}
        rotation={[0, -6, 0]}
        scale={2}
        onClick={() => props.setActiveState(2)}
      >
        <group
          position={[-3.907, -2.853, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane002.geometry}
            material={materials.street}
          />
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials["roow.001"]}
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials["ручка.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Torus003.geometry}
          material={materials["Material.143"]}
          position={[-0.086, -1.854, 8.125]}
          rotation={[0, 0, -1.577]}
          scale={0.079}
        />
        <mesh
          geometry={nodes.Text.geometry}
          material={materials["Material.016"]}
          position={[-3.201, -2.426, 15.75]}
          rotation={[1.564, -0.005, -1.564]}
          scale={2.016}
        />
        <mesh
          geometry={nodes.Plane026.geometry}
          material={materials["glass.004"]}
          position={[-3.221, -1.785, 17.16]}
          rotation={[0, 0, -1.57]}
        />
        <mesh
          geometry={nodes.Plane025.geometry}
          material={materials["Material.108"]}
          position={[9.271, -4.815, 12.065]}
        />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
          position={[-0.217, -1.899, 15.478]}
          scale={0.108}
        />
        <mesh
          geometry={nodes.Cube200.geometry}
          material={materials["Material.129"]}
          position={[-9.121, -1.744, 7.567]}
          rotation={[Math.PI, -0.004, Math.PI]}
          scale={0.098}
        />
        <mesh
          geometry={nodes.Cube172.geometry}
          material={materials["Material.020"]}
          position={[-3.079, -0.244, 16.002]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={0.098}
        />
        <mesh
          geometry={nodes.Cube094.geometry}
          material={materials["Material.032"]}
          position={[-5.786, 4.786, 7.407]}
        />
        <mesh
          geometry={nodes.Cube092.geometry}
          material={materials["Material.034"]}
          position={[-1.918, 2.445, 13.932]}
          scale={1.813}
        />
        <mesh
          geometry={nodes.Cube016.geometry}
          material={materials["Material.148"]}
          position={[-1.855, 4.786, 9.257]}
        />
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.Geb2}
          position={[-4.556, 0.717, 12.22]}
          rotation={[Math.PI, -1.567, Math.PI]}
          scale={3.508}
        />
        <mesh
          geometry={nodes.Plane028.geometry}
          material={materials["Material.143"]}
        />

        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials["Material.143"]}
        />
        <mesh
          geometry={nodes.Plane008_1.geometry}
          material={materials["Material.143"]}
        />
        <mesh
          geometry={nodes.Plane008_2.geometry}
          material={materials["Material.143"]}
        />
      </group>
    </PresentationControls>
  );
}

useGLTF.preload("/FinalGeb2-transformed.glb");
