/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FINALgeb2.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, PresentationControls } from "@react-three/drei";
import { useControls } from "leva";

export function FINALgeb2(props) {
  const { nodes, materials } = useGLTF("/Models/FINALgeb2-transformed.glb");
  const { pos, rot } = useControls("geb2", {
    pos: {
      //{"pos":[136,6,-78]}
      value: [140, 6, -24],
      step: 2,
    },
    rot: { value: [0, 4.6, 0], step: 0.2 },
  });
  return (
    <PresentationControls enabled={true} azimuth={[-0.2, 0.2]} polar={[0, 0]}>
      <group
        name='building6'
        {...props}
        dispose={null}
        position={pos}
        rotation={rot}
        scale={3}
        onClick={() => props.setActiveState(6)}
      >
        <group
          position={[-3.907, -2.853, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane002.geometry}
            material={materials.street}
          />
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials["roow.001"]}
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials["ручка.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Torus003.geometry}
          material={materials["Material.143"]}
          position={[-0.086, -1.854, 8.125]}
          rotation={[0, 0, -1.577]}
          scale={0.079}
        />
        <mesh
          geometry={nodes.Text.geometry}
          material={materials["Material.016"]}
          position={[-3.201, -2.426, 15.75]}
          rotation={[1.564, -0.005, -1.564]}
          scale={2.016}
        />
        <mesh
          geometry={nodes.Plane026.geometry}
          material={materials["glass.004"]}
          position={[-3.221, -1.785, 17.16]}
          rotation={[0, 0, -1.57]}
        />
        <mesh
          geometry={nodes.Plane025.geometry}
          material={materials["Material.108"]}
          position={[9.271, -4.815, 12.065]}
        />
        <mesh
          geometry={nodes.Plane009.geometry}
          material={materials["glass.002"]}
          position={[-4.985, -1.785, 5.386]}
          rotation={[0, -1.57, -1.57]}
        />
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials.glass}
          position={[-0.082, -1.785, 10.322]}
          rotation={[0, 0, -1.57]}
        />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
          position={[-0.217, -1.899, 15.478]}
          scale={0.108}
        />
        <mesh
          geometry={nodes.Cube200.geometry}
          material={materials["Material.129"]}
          position={[-9.121, -1.744, 7.567]}
          rotation={[Math.PI, -0.004, Math.PI]}
          scale={0.098}
        />
        <mesh
          geometry={nodes.Cube172.geometry}
          material={materials["Material.020"]}
          position={[-3.079, -0.244, 16.002]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={0.098}
        />
        <mesh
          geometry={nodes.Cube124.geometry}
          material={materials["Material.063"]}
          position={[-4.38, -6.838, 7.849]}
          rotation={[Math.PI, -1.566, Math.PI]}
          scale={0.098}
        />
        <mesh
          geometry={nodes.Cube119.geometry}
          material={materials["Material.086"]}
          position={[2.448, -3.838, 10.322]}
          scale={0.098}
        />
        <mesh
          geometry={nodes.Cube094.geometry}
          material={materials["Material.032"]}
          position={[-5.786, 4.786, 7.407]}
        />
        <mesh
          geometry={nodes.Cube092.geometry}
          material={materials["Material.034"]}
          position={[-1.918, 2.445, 13.932]}
          scale={1.813}
        />
        <mesh
          geometry={nodes.Cube016.geometry}
          material={materials["Material.148"]}
          position={[-1.855, 4.786, 9.257]}
        />
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.Geb2}
          position={[-4.556, 0.717, 12.22]}
          rotation={[Math.PI, -1.567, Math.PI]}
          scale={3.508}
        />
        <group
          position={[-3.598, -2.927, 4.506]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane123.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            geometry={nodes.Plane123_1.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            geometry={nodes.Plane123_2.geometry}
            material={materials["Material.023"]}
          />
        </group>
        <group
          position={[-3.598, -2.927, 4.506]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane121.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Plane121_1.geometry}
            material={materials["Material.014"]}
          />
        </group>
        <mesh
          geometry={nodes.Street_FLF082.geometry}
          material={materials["Material.002"]}
          position={[-3.598, -2.927, 4.506]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <group
          position={[-4.718, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane107.geometry}
            material={materials["Material.195"]}
          />
          <mesh
            geometry={nodes.Plane107_1.geometry}
            material={materials["Material.196"]}
          />
        </group>
        <group
          position={[-4.718, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane100.geometry}
            material={materials["Material.193"]}
          />
          <mesh
            geometry={nodes.Plane100_1.geometry}
            material={materials["Material.194"]}
          />
        </group>
        <mesh
          geometry={nodes.Street_FLF086.geometry}
          material={materials["Material.189"]}
          position={[-4.718, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <group position={[3.664, -0.97, 10.89]} scale={0.388}>
          <mesh
            geometry={nodes.Circle006.geometry}
            material={materials.Metal_Color_Palette}
          />
          <mesh
            geometry={nodes.Circle006_1.geometry}
            material={materials["Emission_ Color_Palette"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane028.geometry}
          material={materials["Material.143"]}
        />
        {/* <mesh geometry={nodes.Cube038.geometry} material={materials['Material.129']} /> */}
        {/* <mesh geometry={nodes.Cube037.geometry} material={materials['Material.129']} />  */}
        {/* <mesh geometry={nodes.Cube021.geometry} material={materials['Material.129']} /> */}
        {/* <mesh geometry={nodes.Cube015.geometry} material={materials['Material.020']} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.020']} /> */}
        {/* <mesh geometry={nodes.Cube001.geometry} material={materials['Material.020']} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.020']} /> */}
        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials["Material.143"]}
        />
        <mesh
          geometry={nodes.Plane008_1.geometry}
          material={materials["Material.143"]}
        />
        <mesh
          geometry={nodes.Plane008_2.geometry}
          material={materials["Material.143"]}
        />
      </group>
    </PresentationControls>
  );
}

useGLTF.preload("/FINALgeb2-transformed.glb");
