/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FINALgeb9.glb --transform
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, PresentationControls } from "@react-three/drei";
import { useControls } from "leva";
import { useThree } from "@react-three/fiber";

export function FINALgeb9(props) {
  const { nodes, materials } = useGLTF("/Models/FINALgeb9-transformed.glb");
  const { pos, rot } = useControls("geb9", {
    pos: {
      //{"pos":[-78,18,-120]}
      value: [-78, 18, -120],
      step: 2,
    },
    rot: { value: [0, 0, 0], step: 0.2 },
  });

  return (
    <PresentationControls enabled={true} azimuth={[-0.2, 0.2]} polar={[0, 0]}>
      <group
        name='building9'
        {...props}
        dispose={null}
        position={pos}
        rotation={rot}
        scale={3}
        onClick={() => props.setActiveState(1)}
      >
        <group
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials.street}
          />
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials["roow.001"]}
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials["ручка.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["Material.088"]}
          position={[-9.904, -1.513, 12.262]}
          scale={1.39}
        />
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials["Material.090"]}
          position={[-8.585, 1.579, 13.49]}
          rotation={[1.572, 0, 0]}
          scale={0.493}
        />
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials["Material.093"]}
          position={[-4.592, -0.07, 13.49]}
          rotation={[1.572, 0, 0]}
          scale={0.493}
        />
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Material.091"]}
          position={[-8.585, -0.034, 13.49]}
          rotation={[1.572, 0, 0]}
          scale={0.493}
        />
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials["Material.092"]}
          position={[-4.592, 1.579, 13.49]}
          rotation={[1.572, 0, 0]}
          scale={0.493}
        />
        <mesh
          geometry={nodes.Plane006.geometry}
          material={materials["Material.096"]}
          position={[0.091, -0.369, 12.777]}
          rotation={[1.572, 0, 0]}
          scale={0.837}
        />
        <mesh
          geometry={nodes.Plane007.geometry}
          material={materials["Material.097"]}
          position={[0.091, -0.369, 12.777]}
          rotation={[1.572, 0, 0]}
          scale={0.837}
        />
        <mesh
          geometry={nodes.Text.geometry}
          material={materials["Material.104"]}
          position={[2.193, -1.009, 13.669]}
          rotation={[-1.179, 1.549, 2.757]}
          scale={1.34}
        />
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["Material.106"]}
          position={[-6.49, 1.713, 13.504]}
          scale={0.038}
        />
        <mesh
          geometry={nodes.Cylinder040.geometry}
          material={materials["Material.100"]}
          position={[-1.267, 0.514, 12.79]}
          scale={0.043}
        />
        <group
          position={[-0.994, -2.037, 12.881]}
          rotation={[Math.PI, -1.335, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane297.geometry}
            material={materials["dbl_Layer0_001.005"]}
          />
          <mesh
            geometry={nodes.Plane297_1.geometry}
            material={materials["dbl_Layer0_002.005"]}
          />
          <mesh
            geometry={nodes.Plane297_2.geometry}
            material={materials["dbl_Layer0_003.005"]}
          />
          <mesh
            geometry={nodes.Plane297_3.geometry}
            material={materials["dbl_Layer0_004.005"]}
          />
          <mesh
            geometry={nodes.Plane297_4.geometry}
            material={materials["dbl_Layer0_005.005"]}
          />
          <mesh
            geometry={nodes.Plane297_5.geometry}
            material={materials["dbl_Layer0_006.005"]}
          />
          <mesh
            geometry={nodes.Plane297_6.geometry}
            material={materials["dbl_Layer0_007.005"]}
          />
          <mesh
            geometry={nodes.Plane297_7.geometry}
            material={materials["dbl_Layer0_008.005"]}
          />
        </group>
        <group
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane123.geometry}
            material={materials["Material.195"]}
          />
          <mesh
            geometry={nodes.Plane123_1.geometry}
            material={materials["Material.196"]}
          />
          <mesh
            geometry={nodes.Plane123_2.geometry}
            material={materials["Material.197"]}
          />
        </group>
        <group
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane121.geometry}
            material={materials["Material.193"]}
          />
          <mesh
            geometry={nodes.Plane121_1.geometry}
            material={materials["Material.194"]}
          />
        </group>
        <mesh
          geometry={nodes.Street_FLF082.geometry}
          material={materials["Material.184"]}
          position={[-3.907, -2.927, 4.911]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <group
          position={[-4.165, -2.968, -1.839]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane100.geometry}
            material={materials["Material.337"]}
          />
          <mesh
            geometry={nodes.Plane100_1.geometry}
            material={materials["Material.338"]}
          />
        </group>
        <mesh
          geometry={nodes.Street_FLF086.geometry}
          material={materials["Material.333"]}
          position={[-4.165, -2.968, -1.839]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          geometry={nodes.Street_FLF072.geometry}
          material={materials["Bush.009"]}
          position={[-4.165, -2.968, -1.839]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <group
          position={[-4.165, -2.968, -1.839]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane387.geometry}
            material={materials["Material.413"]}
          />
          <mesh
            geometry={nodes.Plane387_1.geometry}
            material={materials["Material.414"]}
          />
        </group>
        {/* <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.100']} /> */}
      </group>
    </PresentationControls>
  );
}

useGLTF.preload("/FINALgeb9-transformed.glb");
