/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FINALgeb6.glb --transform
*/

import React, { useRef } from "react";
import { useGLTF, PresentationControls } from "@react-three/drei";
import { useControls } from "leva";

export function FINALgeb6(props) {
  const { nodes, materials } = useGLTF("/Models/FINALgeb6-transformed.glb");
  const { pos, rot } = useControls("geb6", {
    pos: {
      //{"pos":[20,3,-12]}
      value: [20, 3, -12],
      step: 2,
    },
    rot: { value: [0, -1.5, 0], step: 0.2 },
  });

  return (
    <PresentationControls enabled={true} azimuth={[-0.2, 0.2]} polar={[0, 0]}>
      <group
        name='building9'
        {...props}
        dispose={null}
        position={pos}
        rotation={rot}
        scale={2}
        onClick={() => props.setActiveState(1)}
      >
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.Geb2}
          position={[0.009, 0.715, 1.898]}
          rotation={[Math.PI, -1.567, Math.PI]}
          scale={3.508}
        />
        <mesh
          geometry={nodes.Cube017.geometry}
          material={materials["Material.001"]}
          position={[7.008, -4.733, 0]}
          scale={0.098}
        />
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials.glass}
          position={[4.483, -1.787, 0]}
          rotation={[0, 0, -1.57]}
        />
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials["Material.011"]}
          position={[4.51, -0.336, 0]}
          rotation={[0, 0, -1.573]}
        />
        <mesh
          geometry={nodes.Text.geometry}
          material={materials["Material.016"]}
          position={[4.515, -2.627, -4.013]}
          rotation={[1.634, -0.005, -1.564]}
          scale={1.656}
        />
        <mesh
          geometry={nodes.Text003.geometry}
          material={materials["Material.062"]}
          position={[4.305, -2.595, -4.989]}
          rotation={[1.583, -0.006, -3.135]}
          scale={1.597}
        />
        <mesh
          geometry={nodes.Cube092.geometry}
          material={materials["Material.034"]}
          position={[2.544, 4.254, 3.647]}
        />
        <mesh
          geometry={nodes.Cube093.geometry}
          material={materials["Material.033"]}
          position={[-0.079, 4.784, 3.647]}
        />
        <mesh
          geometry={nodes.Cube094.geometry}
          material={materials["Material.032"]}
          position={[-0.104, 4.784, 0.47]}
          scale={1.459}
        />
        <mesh
          geometry={nodes.Plane018.geometry}
          material={materials["Material.036"]}
          position={[13.836, -1.856, -5.797]}
        />
        <mesh
          geometry={nodes.Cube104.geometry}
          material={materials["Material.035"]}
          position={[7.206, -0.904, 7.515]}
          scale={0.098}
        />
        <mesh
          geometry={nodes.Plane026.geometry}
          material={materials["glass.004"]}
          position={[4.483, -1.787, 0]}
          rotation={[0, 0, -1.57]}
        />
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials["Material.091"]}
          position={[2.741, -1.613, 21.919]}
        />
        <mesh
          geometry={nodes.Plane010.geometry}
          material={materials["glass.005"]}
          position={[2.753, -1.787, 12.662]}
          rotation={[0, 0, -1.57]}
        />
        <group position={[4.882, -1.785, 8.309]}>
          <mesh
            geometry={nodes.Cube131.geometry}
            material={materials["Handlebar.001"]}
          />
          <mesh
            geometry={nodes.Cube131_1.geometry}
            material={materials.Wheel}
          />
          <mesh
            geometry={nodes.Cube131_2.geometry}
            material={materials.Pedals_Seat}
          />
          <mesh
            geometry={nodes.Cube131_3.geometry}
            material={materials.Frame}
          />
          <mesh
            geometry={nodes.Cube131_4.geometry}
            material={materials["Chain.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Circle018.geometry}
          material={materials.Blue}
          position={[5.758, -2.257, 0.862]}
          scale={0.213}
        />
        <mesh
          geometry={nodes.Circle017.geometry}
          material={materials.Metallic}
          position={[5.722, -2.37, 0.862]}
          scale={0.213}
        />
        <group position={[7.416, -2.806, 9.03]} scale={0.115}>
          <mesh
            geometry={nodes.Circle.geometry}
            material={materials.Metal_Color_Palette}
          />
          <mesh
            geometry={nodes.Circle_1.geometry}
            material={materials["Emission_ Color_Palette"]}
          />
        </group>
        <group
          position={[-1.427, -2.853, -7.443]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane008.geometry}
            material={materials["street.001"]}
          />
          <mesh
            geometry={nodes.Plane008_1.geometry}
            material={materials["roow.002"]}
          />
          <mesh
            geometry={nodes.Plane008_2.geometry}
            material={materials["ручка.002"]}
          />
        </group>
        <mesh
          geometry={nodes.Tree001.geometry}
          material={materials["Material.022"]}
          position={[-9.132, -2.748, 16.863]}
          scale={0.275}
        />
        <group
          position={[0.477, -2.927, -4.741]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane297.geometry}
            material={materials["dbl_Layer0_001.018"]}
          />
          <mesh
            geometry={nodes.Plane297_1.geometry}
            material={materials["dbl_Layer0_002.018"]}
          />
          <mesh
            geometry={nodes.Plane297_2.geometry}
            material={materials["dbl_Layer0_003.018"]}
          />
          <mesh
            geometry={nodes.Plane297_3.geometry}
            material={materials["dbl_Layer0_004.018"]}
          />
          <mesh
            geometry={nodes.Plane297_4.geometry}
            material={materials["dbl_Layer0_005.018"]}
          />
          <mesh
            geometry={nodes.Plane297_5.geometry}
            material={materials["dbl_Layer0_006.018"]}
          />
          <mesh
            geometry={nodes.Plane297_6.geometry}
            material={materials["dbl_Layer0_007.018"]}
          />
          <mesh
            geometry={nodes.Plane297_7.geometry}
            material={materials["dbl_Layer0_008.018"]}
          />
        </group>
        <group
          position={[6.989, -1.145, -6.138]}
          rotation={[Math.PI, -0.005, Math.PI]}
          scale={1.324}
        >
          <mesh
            geometry={nodes.Plane123.geometry}
            material={materials["Material.155"]}
          />
          <mesh
            geometry={nodes.Plane123_1.geometry}
            material={materials["Material.156"]}
          />
          <mesh
            geometry={nodes.Plane123_2.geometry}
            material={materials["Material.157"]}
          />
        </group>
        <mesh
          geometry={nodes.Street_FLF082.geometry}
          material={materials["Material.010"]}
          position={[6.373, -2.691, -5.891]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <group
          position={[10.711, -2.927, 16.93]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane114.geometry}
            material={materials["Material.227"]}
          />
          <mesh
            geometry={nodes.Plane114_1.geometry}
            material={materials["Material.228"]}
          />
        </group>
        <group
          position={[10.711, -2.927, 16.93]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane107.geometry}
            material={materials["Material.225"]}
          />
          <mesh
            geometry={nodes.Plane107_1.geometry}
            material={materials["Material.226"]}
          />
        </group>
        <group
          position={[10.711, -2.927, 16.93]}
          rotation={[Math.PI, -0.005, Math.PI]}
        >
          <mesh
            geometry={nodes.Plane100.geometry}
            material={materials["Material.223"]}
          />
          <mesh
            geometry={nodes.Plane100_1.geometry}
            material={materials["Material.224"]}
          />
        </group>
        <mesh
          geometry={nodes.Street_FLF086.geometry}
          material={materials["Material.219"]}
          position={[10.711, -2.927, 16.93]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        {/* <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} /> */}
        {/* <mesh geometry={nodes.Plane005.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.022']} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.035']} />
      <mesh geometry={nodes.Cube052.geometry} material={materials['Material.001']} /> */}
        {/* <mesh geometry={nodes.Cube059.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube060.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube132.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Cube089.geometry} material={materials['Material.035']} /> */}
        {/* <mesh geometry={nodes.Cube089_1.geometry} material={materials['Material.035']} />
      <mesh geometry={nodes.Cube089_2.geometry} material={materials['Material.035']} /> */}
      </group>
    </PresentationControls>
  );
}

useGLTF.preload("/FINALgeb6-transformed.glb");
