/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FINALgeb5.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF, PresentationControls } from '@react-three/drei'
import { useControls } from 'leva'

export function FINALgeb5(props) {
  const { nodes, materials } = useGLTF('/Models/FINALgeb5-transformed.glb')
  const group = useRef();
  const { pos, rot } = useControls("geb5", {
    pos: {
      //{"pos":[-56,-3,64]}
      value: [-56, -3, 64],
      step: 2,
    },
    rot: { value: [0, 0, 0], step: 0.2 },
  });
  return (
    <PresentationControls
    enabled={true}
    azimuth={[-0.05, 0.05]}
    polar={[0, 0]}
  >
    <group  onClick={() => props.setActiveState(4)}
    name='building4'
    ref={group}
    {...props}
    dispose={null}
    position={pos}
    rotation={rot}
    scale={2.2} >
      <group position={[0.356, -2.853, -15.024]} rotation={[Math.PI, -0.005, Math.PI]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials.street} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['roow.001']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['ручка.001']} />
      </group>
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.062']} position={[8.214, -2.599, -12.946]} rotation={[1.583, -0.006, -3.135]} scale={1.597} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.016']} position={[8.424, -2.631, -11.971]} rotation={[1.576, 0.003, -1.567]} scale={1.656} />
      <mesh geometry={nodes.Plane026.geometry} material={materials['glass.004']} position={[8.392, -1.791, -7.958]} rotation={[0, 0, -1.57]} />
      <mesh geometry={nodes.Plane024.geometry} material={materials['Material.066']} position={[8.419, 0.375, -7.958]} rotation={[0, 0, -1.573]} />
      <mesh geometry={nodes.Plane021.geometry} material={materials['Material.046']} position={[17.745, -0.883, -6.214]} />
      <mesh geometry={nodes.Cube185.geometry} material={materials['Material.150']} position={[0.961, 5.042, -2.031]} />
      <mesh geometry={nodes.Cube184.geometry} material={materials['Material.021']} position={[2.099, -2.725, 15.647]} rotation={[Math.PI, -1.57, Math.PI]} scale={0.098} />
      <mesh geometry={nodes.Cube157.geometry} material={materials['Material.146']} position={[-2.838, -2.13, -14.911]} rotation={[0, 1.568, 0]} scale={0.098} />
      <mesh geometry={nodes.Cube094.geometry} material={materials['Material.032']} position={[3.805, 4.78, -7.488]} scale={1.459} />
      <mesh geometry={nodes.Cube092.geometry} material={materials['Material.034']} position={[5.372, 4.504, -2.316]} />
      <mesh geometry={nodes.Cube091.geometry} material={materials['Material.026']} position={[4.094, -4.761, -10.43]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
      <mesh geometry={nodes.Circle032.geometry} material={materials.Metallic} position={[9.735, -2.298, -7.134]} rotation={[0, 0.117, 0]} scale={0.167} />
      <group position={[10.259, -2.927, -22.693]} rotation={[Math.PI, -0.005, Math.PI]}>
        <mesh geometry={nodes.Plane114.geometry} material={materials['Material.108']} />
        <mesh geometry={nodes.Plane114_1.geometry} material={materials['Material.109']} />
      </group>
      <group position={[10.259, -2.927, -22.693]} rotation={[Math.PI, -0.005, Math.PI]}>
        <mesh geometry={nodes.Plane107.geometry} material={materials['Material.091']} />
        <mesh geometry={nodes.Plane107_1.geometry} material={materials['Material.095']} />
      </group>
      <group position={[10.259, -2.927, -22.693]} rotation={[Math.PI, -0.005, Math.PI]}>
        <mesh geometry={nodes.Plane100.geometry} material={materials['Material.068']} />
        <mesh geometry={nodes.Plane100_1.geometry} material={materials['Material.073']} />
      </group>
      <mesh geometry={nodes.Street_FLF086.geometry} material={materials['Material.010']} position={[10.259, -2.927, -22.693]} rotation={[Math.PI, -0.005, Math.PI]} />
      <group position={[-7.571, -2.927, 6.623]} rotation={[Math.PI, -0.005, Math.PI]}>
        <mesh geometry={nodes.Plane123.geometry} material={materials['Material.266']} />
        <mesh geometry={nodes.Plane123_1.geometry} material={materials['Material.267']} />
        <mesh geometry={nodes.Plane123_2.geometry} material={materials['Material.268']} />
      </group>
      <group position={[4.449, -2.927, -12.709]} rotation={[Math.PI, -0.005, Math.PI]}>
        <mesh geometry={nodes.Plane297.geometry} material={materials['dbl_Layer0_001.018']} />
        <mesh geometry={nodes.Plane297_1.geometry} material={materials['dbl_Layer0_002.018']} />
        <mesh geometry={nodes.Plane297_2.geometry} material={materials['dbl_Layer0_003.018']} />
        <mesh geometry={nodes.Plane297_3.geometry} material={materials['dbl_Layer0_004.018']} />
        <mesh geometry={nodes.Plane297_4.geometry} material={materials['dbl_Layer0_005.018']} />
        <mesh geometry={nodes.Plane297_5.geometry} material={materials['dbl_Layer0_006.018']} />
        <mesh geometry={nodes.Plane297_6.geometry} material={materials['dbl_Layer0_007.018']} />
        <mesh geometry={nodes.Plane297_7.geometry} material={materials['dbl_Layer0_008.018']} />
      </group>
      <mesh geometry={nodes.Plane022.geometry} material={materials['Material.066']} />
      {/* <mesh geometry={nodes.Cube014.geometry} material={materials['Material.146']} />
      <mesh geometry={nodes.Cube061.geometry} material={materials['Material.021']} />
      <mesh geometry={nodes.Cube059.geometry} material={materials['Material.021']} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.026']} />
      <mesh geometry={nodes.Cube052.geometry} material={materials['Material.026']} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.026']} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.026']} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.021']} /> */}
      <mesh geometry={nodes._Light_Area_Of_Street_lamp_B.geometry} material={materials['Emission_ Color_Palette']} position={[8.924, -2.832, 0]} scale={0.549} />
      <mesh geometry={nodes.Base_Of_Street_Lamp_B.geometry} material={materials.Metal_Color_Palette} position={[8.924, -2.832, 0]} scale={0.549} />
      {/* <mesh geometry={nodes.Cube145.geometry} material={materials['Material.146']} />
      <mesh geometry={nodes.Cube145_1.geometry} material={materials['Material.146']} />
      <mesh geometry={nodes.Cube145_2.geometry} material={materials['Material.146']} /> */}
    </group>
    </PresentationControls>
  )
}

useGLTF.preload('/FINALgeb5-transformed.glb')
