/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FinalGeb3.glb --transform
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
export function Geb1(props) {
  const { scene } = useGLTF("/Models/Geb1.glb");

  return (
    <group onClick={() => props.setActiveState(1)}>
      <primitive
        position={[5, 0, 66]}
        rotation={[0, 6.2, 0]}
        object={scene}
        scale={1.5}
      />
    </group>
  );
}

useGLTF.preload("/Geb1.glb");
