/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 GEB4.glb --transform
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function GEB4(props) {
  const { nodes, materials } = useGLTF(
    "/Models/FahrradStation-transformed.glb"
  );

  return (
    <group
      onClick={() => props.setActiveState(1)}
      {...props}
      dispose={null}
      position={[220, 8, -65]}
      rotation={[0, 0.6, 0]}
      scale={0.8}
    >
      <group name='Scene'>
        <group
          name='house038'
          position={[6.612, 2.728, 6.04]}
          rotation={[1.571, -0.021, -1.569]}
          scale={[3.67, 1.626, 2.516]}
        >
          <mesh
            name='Cube281'
            geometry={nodes.Cube281.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_1'
            geometry={nodes.Cube281_1.geometry}
            material={materials["street.004"]}
          />
          <mesh
            name='Cube281_2'
            geometry={nodes.Cube281_2.geometry}
            material={materials["roow.005"]}
          />
          <mesh
            name='Cube281_3'
            geometry={nodes.Cube281_3.geometry}
            material={materials["ручка.008"]}
          />
          <mesh
            name='Cube281_4'
            geometry={nodes.Cube281_4.geometry}
            material={materials["ручка.008"]}
          />
          <mesh
            name='Cube281_5'
            geometry={nodes.Cube281_5.geometry}
            material={materials["Handlebar.002"]}
          />
          <mesh
            name='Cube281_6'
            geometry={nodes.Cube281_6.geometry}
            material={materials["Wheel.001"]}
          />
          <mesh
            name='Cube281_7'
            geometry={nodes.Cube281_7.geometry}
            material={materials["Pedals_Seat.001"]}
          />
          <mesh
            name='Cube281_8'
            geometry={nodes.Cube281_8.geometry}
            material={materials["Frame.001"]}
          />
          <mesh
            name='Cube281_9'
            geometry={nodes.Cube281_9.geometry}
            material={materials["Chain.002"]}
          />
          <mesh
            name='Cube281_10'
            geometry={nodes.Cube281_10.geometry}
            material={materials["Handlebar.002"]}
          />
          <mesh
            name='Cube281_11'
            geometry={nodes.Cube281_11.geometry}
            material={materials["Wheel.001"]}
          />
          <mesh
            name='Cube281_12'
            geometry={nodes.Cube281_12.geometry}
            material={materials["Pedals_Seat.001"]}
          />
          <mesh
            name='Cube281_13'
            geometry={nodes.Cube281_13.geometry}
            material={materials["Frame.001"]}
          />
          <mesh
            name='Cube281_14'
            geometry={nodes.Cube281_14.geometry}
            material={materials["Chain.002"]}
          />
          <mesh
            name='Cube281_15'
            geometry={nodes.Cube281_15.geometry}
            material={materials["Material.441"]}
          />
          <mesh
            name='Cube281_16'
            geometry={nodes.Cube281_16.geometry}
            material={materials["Material.441"]}
          />
          <mesh
            name='Cube281_17'
            geometry={nodes.Cube281_17.geometry}
            material={materials["Material.441"]}
          />
          <mesh
            name='Cube281_18'
            geometry={nodes.Cube281_18.geometry}
            material={materials["Material.441"]}
          />
          <mesh
            name='Cube281_19'
            geometry={nodes.Cube281_19.geometry}
            material={materials["Material.441"]}
          />
          <mesh
            name='Cube281_20'
            geometry={nodes.Cube281_20.geometry}
            material={materials["Material.441"]}
          />
          <mesh
            name='Cube281_21'
            geometry={nodes.Cube281_21.geometry}
            material={materials.Blue}
          />
          <mesh
            name='Cube281_22'
            geometry={nodes.Cube281_22.geometry}
            material={materials["Material.441"]}
          />
          <mesh
            name='Cube281_23'
            geometry={nodes.Cube281_23.geometry}
            material={materials["Metallic.004"]}
          />
          <mesh
            name='Cube281_24'
            geometry={nodes.Cube281_24.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_25'
            geometry={nodes.Cube281_25.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_26'
            geometry={nodes.Cube281_26.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_27'
            geometry={nodes.Cube281_27.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_28'
            geometry={nodes.Cube281_28.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_29'
            geometry={nodes.Cube281_29.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_30'
            geometry={nodes.Cube281_30.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_31'
            geometry={nodes.Cube281_31.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_32'
            geometry={nodes.Cube281_32.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_33'
            geometry={nodes.Cube281_33.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_34'
            geometry={nodes.Cube281_34.geometry}
            material={materials.wood2}
          />
          <mesh
            name='Cube281_35'
            geometry={nodes.Cube281_35.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_36'
            geometry={nodes.Cube281_36.geometry}
            material={materials.dark}
          />
          <mesh
            name='Cube281_37'
            geometry={nodes.Cube281_37.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_38'
            geometry={nodes.Cube281_38.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_39'
            geometry={nodes.Cube281_39.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_40'
            geometry={nodes.Cube281_40.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_41'
            geometry={nodes.Cube281_41.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_42'
            geometry={nodes.Cube281_42.geometry}
            material={materials.wood2}
          />
          <mesh
            name='Cube281_43'
            geometry={nodes.Cube281_43.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_44'
            geometry={nodes.Cube281_44.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_45'
            geometry={nodes.Cube281_45.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_46'
            geometry={nodes.Cube281_46.geometry}
            material={materials.wood2}
          />
          <mesh
            name='Cube281_47'
            geometry={nodes.Cube281_47.geometry}
            material={materials.wood2}
          />
          <mesh
            name='Cube281_48'
            geometry={nodes.Cube281_48.geometry}
            material={materials.wood2}
          />
          <mesh
            name='Cube281_49'
            geometry={nodes.Cube281_49.geometry}
            material={materials.wood2}
          />
          <mesh
            name='Cube281_50'
            geometry={nodes.Cube281_50.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_51'
            geometry={nodes.Cube281_51.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_52'
            geometry={nodes.Cube281_52.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_53'
            geometry={nodes.Cube281_53.geometry}
            material={materials["wood.014"]}
          />
          <mesh
            name='Cube281_54'
            geometry={nodes.Cube281_54.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_55'
            geometry={nodes.Cube281_55.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_56'
            geometry={nodes.Cube281_56.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_57'
            geometry={nodes.Cube281_57.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_58'
            geometry={nodes.Cube281_58.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_59'
            geometry={nodes.Cube281_59.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_60'
            geometry={nodes.Cube281_60.geometry}
            material={materials["Tree 1.001"]}
          />
          <mesh
            name='Cube281_61'
            geometry={nodes.Cube281_61.geometry}
            material={materials["Door.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Models/FahrradStation-transformed.glb");
