/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Landscapenew.glb --transform
*/

import React, { useEffect } from "react";
import { useFBX, useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { useControls } from "leva";

export function Landscapenew(props) {
  const { nodes, materials } = useGLTF('/Models/Landscapenew-transformed.glb')
  const { camera } = useThree();
  const { position, rotation, modelRotation} = useControls({
    position: {
      value: [268, 37.2, -136],
      step: 2,
    },
    rotation: { value: [0.2, 2.4, -0.2], step: 0.2 },
   modelRotation: { value: [0, 0, 0], step: 0.2 },
  });


  useEffect(() => {
    camera.position.set(...position);
    camera.rotation.set(...rotation);
  }, [position, rotation]);

  return (
    <group name="campus" position={[16.083, -23.741, 31.44]} rotation={modelRotation}  {...props} dispose={null}>
      <mesh geometry={nodes.TexturesCom_Aerials0091_1_M.geometry} material={materials.TexturesCom_Aerials0091_1_M} position={[-7.973, 80.615, -149.985]} rotation={[Math.PI / 2, 0, 0]} scale={403.111} />
      <mesh geometry={nodes.Landscape011.geometry} material={materials.stone} position={[-15.295, -4.329, 24.226]} rotation={[0.51, -0.39, 2.44]} scale={0.221} />
      <mesh geometry={nodes.ground.geometry} material={materials.ground_grass} position={[-7.01, -5.014, -35.988]} scale={83.459} />
      <group position={[67.851, -4.8, 54.405]} scale={0.473}>
        <mesh geometry={nodes.Mesh007.geometry} material={materials['Material #48.008']} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={materials['Material #47.008']} />
        <mesh geometry={nodes.Mesh007_2.geometry} material={materials['Material #111.008']} />
        <mesh geometry={nodes.Mesh007_3.geometry} material={materials['Material #137.008']} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-88.088, -4.312, 48.505]} />
      <group position={[23.797, -0.62, 40.299]} rotation={[0, 0.3, -Math.PI / 2]} scale={0.215}>
        <mesh geometry={nodes.Torus001.geometry} material={materials.metal} />
        <mesh geometry={nodes.Torus001_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Torus001_2.geometry} material={materials.tafel} />
      </group>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.001']} position={[21.481, -2.022, 41.29]} rotation={[1.599, -0.007, -0.304]} scale={1.374} />
      <mesh geometry={nodes.Mesh001.geometry} material={materials['Material #48.008']} />
      <mesh geometry={nodes.Mesh001_1.geometry} material={materials['Material #47.008']} />
      <mesh geometry={nodes.Mesh001_2.geometry} material={materials['Material #47.008']} />
      <mesh geometry={nodes.Mesh001_3.geometry} material={materials['Material #47.008']} />
      <mesh geometry={nodes.Mesh001_4.geometry} material={materials['Material #47.008']} />
      <mesh geometry={nodes.Mesh001_5.geometry} material={materials['Material #47.008']} />
      <mesh geometry={nodes.Mesh001_6.geometry} material={materials['Material #111.008']} />
      <mesh geometry={nodes.Mesh001_7.geometry} material={materials['Material #111.008']} />
      <mesh geometry={nodes.Mesh001_8.geometry} material={materials['Material #137.008']} />
      <mesh geometry={nodes.Mesh001_9.geometry} material={materials['Material #137.008']} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['body_material.001']} />
      <mesh geometry={nodes.Sphere002_1.geometry} material={materials.bulb_casing_material} />
    </group>
  )
}

useGLTF.preload('/Landscapenew-transformed.glb')
