/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 FinalGeb4.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    "/Mdoels/FinalGeb4-transformed.glb"
  );
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Street_FLF001" position={[-3.907, -2.927, 4.911]} rotation={[Math.PI, -0.005, Math.PI]}>
          <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials.street} />
          <mesh name="Plane002_2" geometry={nodes.Plane002_2.geometry} material={materials['roow.001']} />
          <mesh name="Plane002_3" geometry={nodes.Plane002_3.geometry} material={materials['ручка.001']} />
          <mesh name="Plane002_4" geometry={nodes.Plane002_4.geometry} material={materials.street} />
          <mesh name="Plane002_5" geometry={nodes.Plane002_5.geometry} material={materials['roow.001']} />
          <mesh name="Plane002_6" geometry={nodes.Plane002_6.geometry} material={materials['ручка.001']} />
        </group>
        <mesh name="Text003" geometry={nodes.Text003.geometry} material={materials['Material.062']} position={[-7.579, -2.756, 5.266]} rotation={[1.583, -0.006, -3.135]} scale={1.597} />
        <mesh name="Text002" geometry={nodes.Text002.geometry} material={materials['Material.062']} position={[-0.359, -2.756, 5.266]} rotation={[-2.095, -1.547, -0.518]} scale={0.736} />
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.062']} position={[0.323, -2.756, 5.594]} rotation={[-3.121, -0.005, -1.564]} scale={0.736} />
        <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials['Material.062']} position={[0.31, -1.048, 12.967]} rotation={[1.571, -0.005, -1.564]} scale={0.574} />
        <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials['Material.046']} position={[9.644, -0.934, 11.998]} />
        <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials['Material.046']} position={[9.644, -3, 11.998]} />
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['Material.046']} position={[-1.152, 2.16, 5.308]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.046']} position={[9.644, -1.912, 4.457]} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.031']} position={[-9.361, -4.166, 5.168]} rotation={[-1.571, 0, -0.149]} />
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials['Material.031']} position={[-7.709, -4.166, 5.168]} rotation={[-1.571, 0, -0.149]} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['Material.031']} position={[-6.133, -4.157, 5.168]} rotation={[-1.571, 0, -0.149]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['Material.031']} position={[-4.394, -4.157, 5.168]} rotation={[-1.571, 0, -0.149]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.031']} position={[-2.644, -4.157, 5.168]} rotation={[-1.571, 0, -0.149]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.031']} position={[0.308, -4.157, 9.233]} rotation={[-1.57, 0, -1.573]} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Material.031']} position={[-2.672, -0.392, 5.262]} rotation={[0, 1.555, -1.573]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.031']} position={[-8.559, -0.395, 10.255]} rotation={[0, 0, -1.573]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.031']} position={[-8.559, 0.2, 10.255]} rotation={[0, 0, -1.573]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['glass.002']} position={[-4.612, -1.843, 5.319]} rotation={[0, -1.57, -1.57]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['glass.002']} position={[-8.541, -1.843, 10.255]} rotation={[0, 0, -1.57]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.031']} position={[0.308, -4.157, 10.9]} rotation={[-1.57, 0, -1.573]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.031']} position={[0.318, -0.392, 10.255]} rotation={[0, 0, -1.573]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['glass.002']} position={[0.291, -1.843, 10.255]} rotation={[0, 0, -1.57]} />
        <group name="Layer0_001003" position={[-8.671, -2.126, 6.446]} rotation={[0, -0.629, 0]} scale={0.019}>
          <mesh name="Mesh003" geometry={nodes.Mesh003.geometry} material={materials['dbl_Layer0_001.003']} />
          <mesh name="Mesh003_1" geometry={nodes.Mesh003_1.geometry} material={materials['dbl_Layer0_002.003']} />
          <mesh name="Mesh003_2" geometry={nodes.Mesh003_2.geometry} material={materials['dbl_Layer0_003.003']} />
          <mesh name="Mesh003_3" geometry={nodes.Mesh003_3.geometry} material={materials['dbl_Layer0_003.003']} />
          <mesh name="Mesh003_4" geometry={nodes.Mesh003_4.geometry} material={materials['dbl_Layer0_005.003']} />
          <mesh name="Mesh003_5" geometry={nodes.Mesh003_5.geometry} material={materials['dbl_Layer0_005.003']} />
          <mesh name="Mesh003_6" geometry={nodes.Mesh003_6.geometry} material={materials['dbl_Layer0_005.003']} />
          <mesh name="Mesh003_7" geometry={nodes.Mesh003_7.geometry} material={materials['dbl_Layer0_008.003']} />
        </group>
        <group name="Layer0_001002" position={[-8.671, -2.126, 7.863]} rotation={[0, -0.969, 0]} scale={0.019}>
          <mesh name="Mesh002" geometry={nodes.Mesh002.geometry} material={materials['dbl_Layer0_001.003']} />
          <mesh name="Mesh002_1" geometry={nodes.Mesh002_1.geometry} material={materials['dbl_Layer0_002.003']} />
          <mesh name="Mesh002_2" geometry={nodes.Mesh002_2.geometry} material={materials['dbl_Layer0_003.003']} />
          <mesh name="Mesh002_3" geometry={nodes.Mesh002_3.geometry} material={materials['dbl_Layer0_003.003']} />
          <mesh name="Mesh002_4" geometry={nodes.Mesh002_4.geometry} material={materials['dbl_Layer0_005.003']} />
          <mesh name="Mesh002_5" geometry={nodes.Mesh002_5.geometry} material={materials['dbl_Layer0_005.003']} />
          <mesh name="Mesh002_6" geometry={nodes.Mesh002_6.geometry} material={materials['dbl_Layer0_005.003']} />
          <mesh name="Mesh002_7" geometry={nodes.Mesh002_7.geometry} material={materials['dbl_Layer0_008.003']} />
        </group>
        <group name="Layer0_001001" position={[0.39, -2.126, 8.451]} rotation={[0, -0.969, 0]} scale={0.019}>
          <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials['dbl_Layer0_001.001']} />
          <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials['dbl_Layer0_002.001']} />
          <mesh name="Mesh001_2" geometry={nodes.Mesh001_2.geometry} material={materials['dbl_Layer0_003.001']} />
          <mesh name="Mesh001_3" geometry={nodes.Mesh001_3.geometry} material={materials['dbl_Layer0_004.001']} />
          <mesh name="Mesh001_4" geometry={nodes.Mesh001_4.geometry} material={materials['dbl_Layer0_005.001']} />
          <mesh name="Mesh001_5" geometry={nodes.Mesh001_5.geometry} material={materials['dbl_Layer0_006.001']} />
          <mesh name="Mesh001_6" geometry={nodes.Mesh001_6.geometry} material={materials['dbl_Layer0_007.001']} />
          <mesh name="Mesh001_7" geometry={nodes.Mesh001_7.geometry} material={materials['dbl_Layer0_008.003']} />
        </group>
        <group name="Layer0_001" position={[0.39, -2.126, 7.035]} rotation={[0, -0.629, 0]} scale={0.019}>
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials['dbl_Layer0_001.003']} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.dbl_Layer0_002} />
          <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials['dbl_Layer0_003.003']} />
          <mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials['dbl_Layer0_003.003']} />
          <mesh name="Mesh_4" geometry={nodes.Mesh_4.geometry} material={materials['dbl_Layer0_005.003']} />
          <mesh name="Mesh_5" geometry={nodes.Mesh_5.geometry} material={materials['dbl_Layer0_005.003']} />
          <mesh name="Mesh_6" geometry={nodes.Mesh_6.geometry} material={materials['dbl_Layer0_005.003']} />
          <mesh name="Mesh_7" geometry={nodes.Mesh_7.geometry} material={materials['dbl_Layer0_008.003']} />
        </group>
        <mesh name="Cube121" geometry={nodes.Cube121.geometry} material={materials['Geb2.001']} position={[-4.183, 0.677, 12.153]} rotation={[Math.PI, -1.567, Math.PI]} scale={3.508} />
        <mesh name="Cube120" geometry={nodes.Cube120.geometry} material={materials['Material.061']} position={[-1.077, 1.477, 15.934]} rotation={[0, -1.568, 0]} scale={0.098} />
        <mesh name="Cube119" geometry={nodes.Cube119.geometry} material={materials['Material.061']} position={[-1.077, 1.179, 15.934]} rotation={[0, -1.568, 0]} scale={0.098} />
        <mesh name="Cube118" geometry={nodes.Cube118.geometry} material={materials['Material.061']} position={[-1.077, 0.888, 15.934]} rotation={[0, -1.568, 0]} scale={0.098} />
        <mesh name="Cube117" geometry={nodes.Cube117.geometry} material={materials['Material.061']} position={[-6.331, 1.756, 15.935]} rotation={[Math.PI, -1.57, Math.PI]} scale={0.098} />
        <mesh name="Cube114" geometry={nodes.Cube114.geometry} material={materials['Material.061']} position={[-6.331, 2.344, 15.935]} rotation={[Math.PI, -1.57, Math.PI]} scale={0.098} />
        <mesh name="Cube113" geometry={nodes.Cube113.geometry} material={materials['Material.061']} position={[-8.747, 2.344, 13.488]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.098} />
        <mesh name="Cube110" geometry={nodes.Cube110.geometry} material={materials['Material.061']} position={[-8.747, 1.756, 13.488]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.098} />
        <mesh name="Cube109" geometry={nodes.Cube109.geometry} material={materials['Material.061']} position={[-8.747, 3.822, 7.5]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.098} />
        <mesh name="Cube116" geometry={nodes.Cube116.geometry} material={materials['Material.061']} position={[-6.33, 1.458, 15.935]} rotation={[Math.PI, -1.57, Math.PI]} scale={0.098} />
        <mesh name="Cube115" geometry={nodes.Cube115.geometry} material={materials['Material.061']} position={[-6.33, 2.046, 15.935]} rotation={[Math.PI, -1.57, Math.PI]} scale={0.098} />
        <mesh name="Cube112" geometry={nodes.Cube112.geometry} material={materials['Material.061']} position={[-8.747, 2.046, 13.489]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.098} />
        <mesh name="Cube111" geometry={nodes.Cube111.geometry} material={materials['Material.061']} position={[-8.747, 1.458, 13.489]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.098} />
        <mesh name="Cube108" geometry={nodes.Cube108.geometry} material={materials['Material.061']} position={[-8.747, 3.524, 7.502]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.098} />
        <mesh name="Cube107" geometry={nodes.Cube107.geometry} material={materials['Material.061']} position={[-3.746, -0.667, 2.586]} rotation={[0, 1.568, 0]} scale={0.098} />
        <mesh name="Cube106" geometry={nodes.Cube106.geometry} material={materials['Material.061']} position={[-3.746, -0.368, 2.586]} rotation={[0, 1.568, 0]} scale={0.098} />
        <mesh name="Cube105" geometry={nodes.Cube105.geometry} material={materials['Material.061']} position={[3.014, -0.661, 17.77]} scale={0.098} />
        <mesh name="Cube104" geometry={nodes.Cube104.geometry} material={materials['Material.061']} position={[3.014, -0.959, 17.77]} scale={0.098} />
        <mesh name="Cube103" geometry={nodes.Cube103.geometry} material={materials['Material.061']} position={[3.014, -3.303, 17.77]} scale={0.098} />
        <mesh name="Cube102" geometry={nodes.Cube102.geometry} material={materials['Material.061']} position={[3.014, -3.012, 17.77]} scale={0.098} />
        <mesh name="Cube101" geometry={nodes.Cube101.geometry} material={materials['Material.061']} position={[3.014, -2.714, 17.77]} scale={0.098} />
        <mesh name="Cube100" geometry={nodes.Cube100.geometry} material={materials['Material.061']} position={[2.332, -1.544, 2.586]} rotation={[0, 1.568, 0]} scale={0.098} />
        <mesh name="Cube099" geometry={nodes.Cube099.geometry} material={materials['Material.061']} position={[2.332, -1.842, 2.586]} rotation={[0, 1.568, 0]} scale={0.098} />
        <mesh name="Cube098" geometry={nodes.Cube098.geometry} material={materials['Material.061']} position={[2.332, -2.133, 2.586]} rotation={[0, 1.568, 0]} scale={0.098} />
        <mesh name="Cube097" geometry={nodes.Cube097.geometry} material={materials['Material.061']} position={[3.014, -1.544, 10.067]} scale={0.098} />
        <mesh name="Cube096" geometry={nodes.Cube096.geometry} material={materials['Material.061']} position={[3.014, -1.842, 10.067]} scale={0.098} />
        <mesh name="Cube095" geometry={nodes.Cube095.geometry} material={materials['Material.061']} position={[3.014, -2.133, 10.067]} scale={0.098} />
        <mesh name="Cube094" geometry={nodes.Cube094.geometry} material={materials['Material.032']} position={[-5.413, 4.728, 7.34]} />
        <mesh name="Cube093" geometry={nodes.Cube093.geometry} material={materials['Material.033']} position={[-4.271, 4.728, 13.901]} />
        <mesh name="Cube092" geometry={nodes.Cube092.geometry} material={materials['Material.034']} position={[-1.648, 4.198, 13.901]} />
        <mesh name="Cube091" geometry={nodes.Cube091.geometry} material={materials['Material.026']} position={[-4.007, -4.813, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube090" geometry={nodes.Cube090.geometry} material={materials['Material.026']} position={[-4.007, -5.108, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube089" geometry={nodes.Cube089.geometry} material={materials['Material.026']} position={[-4.007, -5.413, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube088" geometry={nodes.Cube088.geometry} material={materials['Material.026']} position={[-6.055, -6.866, 10.357]} scale={0.098} />
        <mesh name="Cube087" geometry={nodes.Cube087.geometry} material={materials['Material.026']} position={[-6.055, -6.562, 10.357]} scale={0.098} />
        <mesh name="Cube086" geometry={nodes.Cube086.geometry} material={materials['Material.026']} position={[-6.055, -6.266, 10.357]} scale={0.098} />
        <mesh name="Cube085" geometry={nodes.Cube085.geometry} material={materials['Material.026']} position={[-6.055, -5.971, 10.357]} scale={0.098} />
        <mesh name="Cube084" geometry={nodes.Cube084.geometry} material={materials['Material.026']} position={[-6.055, -5.676, 10.357]} scale={0.098} />
        <mesh name="Cube083" geometry={nodes.Cube083.geometry} material={materials['Material.026']} position={[-6.055, -5.38, 10.357]} scale={0.098} />
        <mesh name="Cube082" geometry={nodes.Cube082.geometry} material={materials['Material.026']} position={[-6.055, -5.089, 10.357]} scale={0.098} />
        <mesh name="Cube081" geometry={nodes.Cube081.geometry} material={materials['Material.026']} position={[-6.055, -4.802, 10.357]} scale={0.098} />
        <mesh name="Cube080" geometry={nodes.Cube080.geometry} material={materials['Material.026']} position={[-4.007, -6.87, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube079" geometry={nodes.Cube079.geometry} material={materials['Material.026']} position={[-4.007, -6.566, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube078" geometry={nodes.Cube078.geometry} material={materials['Material.026']} position={[-4.007, -6.271, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube077" geometry={nodes.Cube077.geometry} material={materials['Material.026']} position={[-4.007, -5.975, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube076" geometry={nodes.Cube076.geometry} material={materials['Material.026']} position={[-4.007, -5.68, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube075" geometry={nodes.Cube075.geometry} material={materials['Material.026']} position={[-4.007, -5.385, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube074" geometry={nodes.Cube074.geometry} material={materials['Material.026']} position={[-4.007, -5.093, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube073" geometry={nodes.Cube073.geometry} material={materials['Material.026']} position={[-4.007, -4.806, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube072" geometry={nodes.Cube072.geometry} material={materials['Material.026']} position={[-4.007, -0.078, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube071" geometry={nodes.Cube071.geometry} material={materials['Material.026']} position={[-4.007, -0.365, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube070" geometry={nodes.Cube070.geometry} material={materials['Material.026']} position={[-4.007, -0.656, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube069" geometry={nodes.Cube069.geometry} material={materials['Material.026']} position={[-4.007, -0.952, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube068" geometry={nodes.Cube068.geometry} material={materials['Material.026']} position={[-4.007, -1.247, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube067" geometry={nodes.Cube067.geometry} material={materials['Material.026']} position={[-4.007, -1.542, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube066" geometry={nodes.Cube066.geometry} material={materials['Material.026']} position={[-4.007, -1.838, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube065" geometry={nodes.Cube065.geometry} material={materials['Material.026']} position={[-4.007, -2.133, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials['Material.026']} position={[-4.007, -2.429, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube063" geometry={nodes.Cube063.geometry} material={materials['Material.026']} position={[-4.007, -2.716, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube062" geometry={nodes.Cube062.geometry} material={materials['Material.026']} position={[-4.007, -3.008, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube061" geometry={nodes.Cube061.geometry} material={materials['Material.026']} position={[-4.007, -3.303, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube060" geometry={nodes.Cube060.geometry} material={materials['Material.026']} position={[-4.007, -3.598, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials['Material.026']} position={[-4.007, -3.894, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={materials['Material.026']} position={[-4.007, -4.189, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials['Material.026']} position={[-4.007, -4.493, 18.209]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube056" geometry={nodes.Cube056.geometry} material={materials['Material.026']} position={[-4.007, -4.493, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials['Material.026']} position={[-4.007, -4.189, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials['Material.026']} position={[-4.007, -3.894, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials['Material.026']} position={[-4.007, -3.598, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials['Material.026']} position={[-4.007, -3.303, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube051" geometry={nodes.Cube051.geometry} material={materials['Material.026']} position={[-4.007, -3.008, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube050" geometry={nodes.Cube050.geometry} material={materials['Material.026']} position={[-4.007, -2.716, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube049" geometry={nodes.Cube049.geometry} material={materials['Material.026']} position={[-4.007, -2.429, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube048" geometry={nodes.Cube048.geometry} material={materials['Material.026']} position={[-4.007, -2.133, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube047" geometry={nodes.Cube047.geometry} material={materials['Material.026']} position={[-4.007, -1.838, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials['Material.026']} position={[-4.007, -1.542, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube045" geometry={nodes.Cube045.geometry} material={materials['Material.026']} position={[-4.007, -1.247, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={materials['Material.026']} position={[-4.007, -0.952, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube043" geometry={nodes.Cube043.geometry} material={materials['Material.026']} position={[-4.007, -0.656, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials['Material.026']} position={[-4.007, -0.365, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials['Material.026']} position={[-4.007, -0.078, 7.782]} rotation={[Math.PI, -1.566, Math.PI]} scale={0.098} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials['Material.026']} position={[-6.055, -0.078, 10.255]} scale={0.098} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials['Material.026']} position={[-6.055, -0.365, 10.255]} scale={0.098} />
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['Material.026']} position={[-6.055, -0.656, 10.255]} scale={0.098} />
        <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['Material.026']} position={[-6.055, -0.952, 10.255]} scale={0.098} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['Material.026']} position={[-6.055, -1.247, 10.255]} scale={0.098} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['Material.026']} position={[-6.055, -1.542, 10.255]} scale={0.098} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['Material.026']} position={[-6.055, -1.838, 10.255]} scale={0.098} />
        <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials['Material.026']} position={[-6.055, -2.133, 10.255]} scale={0.098} />
        <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials['Material.026']} position={[-6.055, -2.429, 10.255]} scale={0.098} />
        <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials['Material.026']} position={[-6.055, -2.716, 10.255]} scale={0.098} />
        <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials['Material.026']} position={[-6.055, -3.008, 10.255]} scale={0.098} />
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials['Material.026']} position={[-6.055, -3.303, 10.255]} scale={0.098} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials['Material.026']} position={[-6.055, -3.598, 10.255]} scale={0.098} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials['Material.026']} position={[-6.055, -3.894, 10.255]} scale={0.098} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials['Material.026']} position={[-6.055, -4.189, 10.255]} scale={0.098} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['Material.026']} position={[-6.055, -4.493, 10.255]} scale={0.098} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['Material.026']} position={[2.816, -4.493, 10.255]} scale={0.098} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['Material.026']} position={[2.816, -4.189, 10.255]} scale={0.098} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.026']} position={[2.816, -3.894, 10.255]} scale={0.098} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.026']} position={[2.816, -3.598, 10.255]} scale={0.098} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.026']} position={[2.816, -3.303, 10.255]} scale={0.098} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.026']} position={[2.816, -3.008, 10.255]} scale={0.098} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.026']} position={[2.816, -2.716, 10.255]} scale={0.098} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.026']} position={[2.816, -2.429, 10.255]} scale={0.098} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.026']} position={[2.816, -2.133, 10.255]} scale={0.098} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.026']} position={[2.816, -1.838, 10.255]} scale={0.098} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.026']} position={[2.816, -1.542, 10.255]} scale={0.098} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.026']} position={[2.816, -1.247, 10.255]} scale={0.098} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.026']} position={[2.816, -0.952, 10.255]} scale={0.098} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.026']} position={[2.816, -0.656, 10.255]} scale={0.098} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.026']} position={[2.816, -0.365, 10.255]} scale={0.098} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.026']} position={[2.816, -0.078, 10.255]} scale={0.098} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['Material.026']} position={[2.816, -6.858, 10.255]} scale={0.098} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['Material.026']} position={[2.816, -6.575, 10.255]} scale={0.098} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Material.026']} position={[2.816, -6.293, 10.255]} scale={0.098} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['Material.026']} position={[2.816, -6.001, 10.255]} scale={0.098} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Material.026']} position={[2.816, -5.7, 10.255]} scale={0.098} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['Material.026']} position={[2.816, -5.391, 10.255]} scale={0.098} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['Material.026']} position={[2.816, -5.09, 10.255]} scale={0.098} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['Material.026']} position={[2.816, -4.789, 10.255]} scale={0.098} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.Geb2} position={[-4.183, 0.659, 12.153]} rotation={[Math.PI, -1.567, Math.PI]} scale={3.508} />
        <group name="Tree013" position={[3.811, -2.875, 15.782]} scale={0.219}>
          <mesh name="Cube043_1" geometry={nodes.Cube043_1.geometry} material={materials['Material.026']} />
          <mesh name="Cube043_2" geometry={nodes.Cube043_2.geometry} material={materials['Material.026']} />
          <mesh name="Cube043_3" geometry={nodes.Cube043_3.geometry} material={materials['Material.026']} />
        </group>
        <group name="Tree011" position={[3.125, -2.921, 16.251]} scale={0.278}>
          <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['Material.026']} />
          <mesh name="Cylinder011_1" geometry={nodes.Cylinder011_1.geometry} material={materials['Material.026']} />
        </group>
        <group name="Tree009" position={[-10.664, -2.867, 13.537]} rotation={[0.012, 0.049, -0.009]} scale={0.225}>
          <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['Material.026']} />
          <mesh name="Cylinder011_1" geometry={nodes.Cylinder011_1.geometry} material={materials['Material.026']} />
        </group>
        <group name="Tree007" position={[-10.342, -1.355, 12.804]} rotation={[Math.PI, -0.902, Math.PI]} scale={0.298}>
          <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['Material.026']} />
          <mesh name="Cylinder006_1" geometry={nodes.Cylinder006_1.geometry} material={materials['Material.026']} />
        </group>
        <group name="Tree002" position={[-11.069, -2.23, 13.012]} rotation={[0.012, 0.049, -0.009]} scale={0.126}>
          <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['Material.026']} />
          <mesh name="Cylinder006_1" geometry={nodes.Cylinder006_1.geometry} material={materials['Material.026']} />
        </group>
        <mesh name="Grass005" geometry={nodes.Grass005.geometry} material={materials['Material.026']} position={[3.506, -2.88, 16.241]} rotation={[Math.PI, -1.548, Math.PI]} scale={0.389} />
        <mesh name="Grass001" geometry={nodes.Grass001.geometry} material={materials['Material.026']} position={[3.061, -2.88, 16.511]} rotation={[2.945, -1.137, 2.819]} scale={0.389} />
        <mesh name="Grass002" geometry={nodes.Grass002.geometry} material={materials['Material.026']} position={[-10.263, -2.88, 13.003]} rotation={[Math.PI, -1.548, Math.PI]} scale={0.389} />
        <mesh name="Grass003" geometry={nodes.Grass003.geometry} material={materials['Material.026']} position={[-10.708, -2.807, 13.274]} rotation={[2.945, -1.137, 2.819]} scale={0.389} />
        <mesh name="Grass004" geometry={nodes.Grass004.geometry} material={materials['Material.026']} position={[-11.222, -2.903, 12.939]} rotation={[2.612, 0.205, -2.954]} scale={0.389} />
        <mesh name="Grass006" geometry={nodes.Grass006.geometry} material={materials['Material.026']} position={[-10.891, -2.858, 13.338]} rotation={[2.815, -0.153, -2.832]} scale={0.389} />
        <group name="Tree001" position={[3.403, -1.611, 15.274]} rotation={[0, 0.922, 0]} scale={0.219}>
          <mesh name="Cube044_1" geometry={nodes.Cube044_1.geometry} material={materials['Material.026']} />
          <mesh name="Cube044_2" geometry={nodes.Cube044_2.geometry} material={materials['Material.026']} />
          <mesh name="Cube044_3" geometry={nodes.Cube044_3.geometry} material={materials['Material.026']} />
        </group>
        <group name="Cube122" position={[3.457, -2.177, 9.392]} rotation={[Math.PI, -0.755, Math.PI]} scale={[0.052, 0.005, 0.104]}>
          <mesh name="Cube045_1" geometry={nodes.Cube045_1.geometry} material={materials.Material} />
          <mesh name="Cube045_2" geometry={nodes.Cube045_2.geometry} material={materials['Blue paint']} />
          <mesh name="Cube045_3" geometry={nodes.Cube045_3.geometry} material={materials['Blue paint']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/FinalGeb4-transformed.glb')
